version: '3.8'

networks:
  serving_prod_net:
    external: true

services:
  reporting:
    container_name: reporting
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WORKSPACE_PATH=/app/evidently_workspace
    volumes:
      - ../data:/data
      - reporting_workspace:/app/evidently_workspace
    ports:
      - "8082:8082"
    networks:
      - serving_prod_net

volumes:
  reporting_workspace:
